version: "3.8"

services:
  app:
    container_name: node-app
    image: node-app
    build:
      context: .
      target: node-app
      dockerfile: Dockerfile.dockerfile
    ports:
      - 8081:8081

  srv:
    container_name: spring-boot-app
    image: spring-boot-app
    build:
      context: .
      target: spring-app
      dockerfile: Dockerfile.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    links:
      - postgresql

  postgresql:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demodb
    ports:
      - "5432:5432"